name: specta_userbot_telegram
description: A sample command-line application.
version: 0.0.0
homepage: https://github.com/azkadev/specta_userbot_telegram.git
repository: https://github.com/azkadev/specta_userbot_telegram.git
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  galaxeus: ^0.0.5
  galaxeus_lib: ^0.0.17
  hive: ^2.2.3
  path: ^1.8.2
  telegram_client: ^0.3.58